### ISSUE TITLE
virus detected

### ISSUE THREAD

**Issue by goofygoobah** [CodeStix/FNAFOnline#11]
i cant use gamejolt to download because it says that there is a virus detected. i did keep anyway and allat but it eventually says windows antivirus blocked this download. could you help me? if i try running from source it says its a trojan

**Comment by goofygoobah** [comment]
i dont know if i trust this game anymore

**Comment by CodeStix** [comment]
Did you end up removing it or? Can you show a screenshot?

**Comment by goofygoobah** [comment]
![image](https://github.com/CodeStix/FNAFOnline/assets/158089548/142e883e-b373-4a5d-98ce-cbd6a39e26bd)
