### ISSUE TITLE
it says its a trojan

### ISSUE THREAD

**Issue by goofygoobah** [CodeStix/FNAFOnline#13]
gamejolt says its a virus

**Comment by CodeStix** [comment]
Really? Can you show a screenshot?

**Comment by goofygoobah** [comment]
Yeah sure!

**Comment by goofygoobah** [comment]
![image](https://github.com/CodeStix/FNAFOnline/assets/158089548/c99df81d-56bd-45cd-bcf0-2bf7f60518f2)
![image](https://github.com/CodeStix/FNAFOnline/assets/158089548/5dfaff57-2982-43ac-9529-4afc95687f3a)

**Comment by goofygoobah** [comment]
but thanks for updating the multiplayer services issue, I really like this project, i starred it ;)
