### ISSUE TITLE
FNAF Online Help ME

### ISSUE THREAD

**Issue by tuu123** [CodeStix/FNAFOnline#9]
![Capture](https://github.com/CodeStix/FNAFOnline/assets/152691894/2863311a-589f-4ce5-b4cc-6e22b30c56a2)
Connecting to the FNAF online services (60%) freeze how to fix

**Comment by Tonkla004** [comment]
Same

**Comment by goofygoobah** [comment]
smae

**Comment by CodeStix** [comment]
[Fixed in new version.](https://gamejolt.com/games/FNAF-online/397267) Sorry for the long wait!
